name: run-tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: set enviroment variables
        run: |
          echo 'PGDATABASE=pokemon_api_v3' > ./database/.env.development
          echo 'PGDATABASE=pokemon_api_v3_test' > ./database/.env.test

      - name: setup the database
        run: |
          npm run database:setup
          npm run database:seed

      - name: run the test script
        run: npm test
