name: run-tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: setup postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgres db: pokemon_api_v3_test

      - name: run the test script
        run: npm test
