name: run-tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: setup postgres
        uses: harmon758/postgresql-action@v1

      - name: install dependencies
        run: npm install

      - name: run the test
        run: npm test
